name: Conditional workflow

on:
  push:
    paths:
      - "backend/**" # triggers action only push in `backend` folder

jobs:
  conditional-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Build backend image
        run: echo "backend image is building"
